name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git checkout --orphan gh-pages
          git --work-tree client/dist add --all
          git --work-tree client/dist commit -m "Deploy to GitHub Pages"
          git push origin HEAD:gh-pages --force